CREATE TABLE end_cliente_bairro(
    id_endereco     INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    logradouro      VARCHAR(30) NOT NULL,
    numero          INTEGER     NOT NULL,
    complemento     CHAR(7),
    id_bairro       INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    referencia      VARCHAR(50) NOT NULL
);


CREATE TABLE end_cliente_cidade(
    id_cidade      INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(30) NOT NULL
    );
    

CREATE TABLE end_cliente_estado(
    id_estado    INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR(30) NOT NULL
);


CREATE TABLE end_cliente_pais(
    id_pais     INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    nome        VARCHAR(30) NOT NULL
);


